# 넘파이


NumPy는 파이썬에서 대규모 수치 데이터를 빠르게 처리하기 위한 배열 연산 라이브러리입니다.  
Pandas, 시각화, 머신러닝 라이브러리 대부분이 내부적으로 NumPy 배열을 사용합니다.

In [109]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [110]:
alist = [1,2,3,4,5] * 3

print(alist)

blist = np.array([1,2,3,4,5])*3

print(blist)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


In [111]:
import numpy

arr = [71000, 71500, 70800, 72000, 72300]
prices = numpy.array(arr)

type(arr), type(prices), arr*2, prices*2


(list,
 numpy.ndarray,
 [71000, 71500, 70800, 72000, 72300, 71000, 71500, 70800, 72000, 72300],
 array([142000, 143000, 141600, 144000, 144600]))

## 넘파이 배열, ndarray

### 1차원, 2차원, 3차원 배열

In [112]:
arr_1 = np.array([1, 2, 3, 4, 5])            # 1차원 # axis = 0
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])     # 2차원 (행렬) # axis = 0, 1
arr_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3차원 # axis = 0, 1, 2

arr_1.shape, arr_2.shape, arr_3.shape

((5,), (2, 3), (2, 2, 2))

### 넘파이 배열의 데이터 타입(dtype)

In [113]:
a = np.array([1, 2, 3])
print(a.dtype)                    # int64 : data가 64bit 정수

b = np.array([1, 2, 3], dtype=float)
print(b.dtype)                    # float64 : data가 64bit 실수

a.itemsize # 8바이트 정수

int64
float64


8

### 넘파이 배열의 속성

|속성|설명|
|--|--|
|ndarray.shape|배열의 각 축(axis)의 크기|
|ndarray.ndim|축의 개수(차원)|
|ndarray.dtype|각 요소의 타입|
|ndarray.itemsize|각 요소 타입의 byte 크기|
|ndarray.size|전체 요소의 개수|

In [114]:
a = np.arange(6).reshape(2, 3)
print(a.shape)     # (3, 4)
print(a.ndim)      # 2
print(a.dtype)     # int64
print(a.itemsize)  # 8
print(a.size)      # 12
print(a)

(2, 3)
2
int64
8
6
[[0 1 2]
 [3 4 5]]


In [115]:
arr1 = np.array([1,0,3,5])

arr1, arr1.shape, np.sum(arr1,axis=0)

(array([1, 0, 3, 5]), (4,), np.int64(9))

In [116]:
arr2 = np.array([[3.3, 2.7, 0.1, 2.1],[0.1, 9.9, 5.4, 6.2]])

arr2, arr2.shape
# 2차원에선 axis = 0이 행방향(열 중심) => 결과: 행 사라짐
np.sum(arr2,axis=0)
# axis = 1 열방향(행 중심) => 결과: 열이 사라짐
np.sum(arr2, axis=1)

array([ 8.2, 21.6])

In [117]:
arr3 = np.arange(24).reshape(2,3,4)
print(arr3)
print("--axis=0--")
print(np.sum(arr3, axis=0))
print("--axis=1--")
print(np.sum(arr3, axis=1))
print("--axis=2--")
print(np.sum(arr3, axis=2))
print("--------")

arr2_1 = np.array([[ 0,  1,  2,  3],
  [ 4,  5,  6,  7],
  [ 8,  9, 10, 11]])
print(arr2_1)
print("-@axis=0@-")
print(np.sum(arr2_1, axis=0))
print("-@axis=1@-")
print(np.sum(arr2_1, axis=1))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--axis=0--
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
--axis=1--
[[12 15 18 21]
 [48 51 54 57]]
--axis=2--
[[ 6 22 38]
 [54 70 86]]
--------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-@axis=0@-
[12 15 18 21]
-@axis=1@-
[ 6 22 38]


### 넘파이 배열의 장점 — 요소별 연산과 브로드캐스팅

파이썬 리스트에 *2를 하면 리스트가 2배로 이어붙여지지만, 넘파이 배열은 각 요소에 2를 곱합니다.  
이렇게 배열의 크기가 달라도 작은 배열을 자동으로 확장해 연산하는 것을 브로드캐스팅이라고 합니다.

In [118]:
py_list = [1, 2, 3]
print(py_list * 2)        # [1, 2, 3, 1, 2, 3]  (리스트 반복)

np_arr = np.array([1, 2, 3])
print(np_arr * 2)         # [2 4 6]             (브로드캐스팅)


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [119]:
# 3종목 x 4일 종가 (3,4)
prices = np.array([
  [71000, 71500, 70800, 72000],
  [62000, 61800, 62200, 61500],
  [155000, 154000, 156000, 153000],
])

# 날짜별 환율
fee = np.array([100,100,150,150])

prices.shape, fee.shape

# 계산하면 fee.shape가 복제되어 3열(3줄)의 2차원으로 변형

print(prices-fee)

fee_rate = np.array([[0.001],[0.0015],[0.002]])
fee_rate.shape

# 계산시에 복제 => [[a,a,a,a],[b,b,b,b],[c,c,c,c]]
print(prices * fee_rate)

[[ 70900  71400  70650  71850]
 [ 61900  61700  62050  61350]
 [154900 153900 155850 152850]]
[[ 71.    71.5   70.8   72.  ]
 [ 93.    92.7   93.3   92.25]
 [310.   308.   312.   306.  ]]


### 다양한 배열 생성 함수

|함수|설명|
|--|--|
|np.zeros(shape)|모든 요소를 0으로 초기화|
|np.ones(shape)|모든 요소를 1로 초기화|
|np.empty(shape)|초기화되지 않은 배열(임의값)|
|np.arange(시작,끝,간격)|일정 간격 배열, 끝값 미포함|
|np.linspace(시작,끝,개수)|구간을 균등 분할, 끝값 포함|


In [120]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=int)
np.arange(10, 30, 5)          # [10 15 20 25]
np.linspace(1, 10, 10)        # 1~10을 10개로 균등 분할

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [121]:
np.array([1,2,3])
np.arange(24).reshape(2,3,4)

np.zeros((2,3,4))

np.empty((2,3,4))

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### [LAB 2-1] 배열 생성과 속성 확인   난이도 ★☆☆   예상 소요 15분
💰 시나리오 : 5개 종목의 오늘 종가를 배열로 만들고 속성을 확인합니다.  
힌트 · closes = np.array([71000, 62000, 155000, 210000, 89000])를 만드세요.  
힌트 · shape, ndim, dtype, size를 각각 출력하세요.  
힌트 · np.zeros(5)로 초기 매수량 배열을 만들어보세요.  
TODO : closes 배열을 만들고 속성 4가지와 zeros(5) 배열을 출력하세요.


In [122]:
closes = np.array([71000, 62000, 155000, 210000, 89000])

print(closes.shape, closes.ndim, closes.dtype, closes.size)

np.zeros(5)

(5,) 1 int64 5


array([0., 0., 0., 0., 0.])

### [LAB 2-2] 원화 종가 → 달러 환산 (브로드캐스팅)   난이도 ★★☆   예상 소요 15분
💰 시나리오 : 해외 리포트용으로 원화 종가 배열을 달러로 환산해야 합니다.  
힌트 · krw_prices = np.array([71000, 62000, 155000, 210000, 89000])를 만드세요.  
힌트 · 환율 exchange_rate = 1380.0으로 나누면 브로드캐스팅으로 전체 배열이 한 번에 환산됩니다.  
힌트 · usd_prices = krw_prices / exchange_rate 를 출력하세요.  
TODO : krw_prices를 달러로 환산한 usd_prices 배열을 브로드캐스팅으로 계산해 출력하세요.  


exchange_rate라는 1개짜리 단일 값(Scalar)을 연산할 때,  
크기를 맞추기 위해 스칼라 값이 배열의 크기만큼 자동으로 확장되어 요소별(Element-wise) 연산이 진행됩니다.  
[1380.0,  1380.0,  1380.0,  1380.0,  1380.0 ]  (exchange_rate 가 브로드캐스팅 됨)


In [123]:
krw_prices = np.array([71000, 62000, 155000, 210000, 89000])

exchange_rate = 1380.0

usd_prices = krw_prices / exchange_rate

print(usd_prices)

[ 51.44927536  44.92753623 112.31884058 152.17391304  64.49275362]


## 넘파이 배열로 다양하게 연산하기

### 요소별 연산 — 사칙연산 · 행렬곱 · 비교연산

In [124]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a - b)   # [-3 -3 -3]
print(a * b)   # [4 10 18]  (요소별 곱셈)
print(a / b)   # [0.25 0.4 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [125]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print(A * B)   # 요소별 곱셈
print(A @ B)   # 행렬 곱셈 (내적)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [126]:
A = np.array([1, 2, 3])
B = np.array([2])
print(A > B)   # [False False True]

[False False  True]


### 수학 함수 · 집계 함수와 벡터화 연산

In [127]:
a = np.array([1, 4, 9])
print(np.sqrt(a))   # [1. 2. 3.]

[1. 2. 3.]


In [128]:
a = np.arange(8).reshape(2, 4) ** 2
print(a)
print(a.sum())      # 전체 합
print(a.mean())     # 전체 평균
print(a.min())      # 최솟값
print(a.max())      # 최댓값
print(a.cumsum())   # 누적합
print(a.argmax())   # 최댓값의 인덱스

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


### 집계 함수에 축(axis) 사용하기

주의:  
axis=0은 '행 방향으로 내려가며' 즉 열마다 하나의 결과를, axis=1은 '열 방향으로 가로질러' 즉 행마다 하나의 결과를 만듭니다.  
처음에는 헷갈리기 쉬우니 결과의 shape을 함께 확인하는 습관을 들이세요.

In [129]:
a = np.array([[0, 1, 4, 9], [16, 25, 36, 49]])

print(a.sum(axis=0))   # 열 기준 : [16 26 40 58]
print(a.sum(axis=1))   # 행 기준 : [14 126]

[16 26 40 58]
[ 14 126]


### [LAB 3-1] 사칙연산과 비교연산   난이도 ★☆☆   예상 소요 15분
💰 시나리오 : 두 종목의 5일 종가 배열로 가격 차이(스프레드)를 계산합니다.  
힌트 · stock_a, stock_b 두 배열(각 5개)을 만드세요.  
힌트 · 스프레드 = stock_a - stock_b를 계산하세요.  
힌트 · stock_a > stock_b 비교 연산으로 A가 더 비쌌던 날을 True/False로 확인하세요.  
TODO : 두 종목 배열을 만들고 스프레드와 비교 연산 결과를 각각 출력하세요.  

In [130]:
stock_a = np.array([2,0,4,1,6])
stock_b = np.array([1,2,3,4,5])

stock = stock_a-stock_b

result = stock_a>stock_b

print(stock, result)

[ 1 -2  1 -3  1] [ True False  True False  True]


### [LAB 3-2] 일별 수익률 계산 (벡터화 연산)   난이도 ★★★   예상 소요 25분
💰 시나리오 : 종가 배열만으로 반복문 없이 일별 수익률을 계산해야 합니다. 수익률 = (오늘종가 - 어제종가) / 어제종가  
힌트 · prices = np.array([71000, 71500, 70800, 72000, 72300, 71900])처럼 6일치 종가를 만드세요.  
힌트 · 오늘 종가는 prices[1:], 어제 종가는 prices[:-1] 슬라이싱으로 얻을 수 있습니다. 두 배열의 길이가 같아 요소별 연산이 가능합니다.  
힌트 · returns = (prices[1:] - prices[:-1]) / prices[:-1] 로 일별 수익률 배열을 구하세요.  
힌트 · np.round(returns * 100, 2)로 퍼센트(%)로 변환해 출력하세요.  
TODO : for문 없이 슬라이싱과 벡터화 연산만으로 일별 수익률 배열을 계산해 퍼센트로 출력하세요.  


[71500 70800 72000 72300 71900]  
[71000 71500 70800 72000 72300]  




In [131]:
prices = np.array([71000, 71500, 70800, 72000, 72300, 71900])

today = prices[1:] # : index 1부터 끝까지
yesterday = prices[:-1] # : index 0<=index<끝

print(today, yesterday)

returns = (prices[1:] - prices[:-1]) / prices[:-1]

result = np.round(returns * 100, 2)

print(result)


#---

result = []
prices = [71000, 71500, 70800, 72000, 72300, 71900]

for index, data in enumerate(prices):
  if index!=0 :
    today = data
    yesterday = prices[index-1]
    returns = (today-yesterday)/yesterday
    result.append(returns)

result = [round(result*100,2) for result in result]

print(result)

[71500 70800 72000 72300 71900] [71000 71500 70800 72000 72300]
[ 0.7  -0.98  1.69  0.42 -0.55]
[0.7, -0.98, 1.69, 0.42, -0.55]


### [LAB 3-3] 포트폴리오 수익률 (행렬곱)   난이도 ★★★   예상 소요 20분
💰 시나리오 : 3종목에 대해 비중을 다르게 투자한 포트폴리오의 전체 수익률을 한 번에 계산합니다.  
힌트 · weights = np.array([0.5, 0.3, 0.2])  # 종목별 투자 비중 (합계 1.0)  
힌트 · stock_returns = np.array([0.02, -0.01, 0.015])  # 종목별 오늘 수익률  
힌트 · 포트폴리오 전체 수익률은 두 벡터의 내적(@ 연산 또는 np.dot)으로 한 번에 계산됩니다.  
TODO : weights와 stock_returns의 행렬곱(@ 연산)으로 포트폴리오 전체 수익률을 계산해 퍼센트로 출력하세요.  

round( 값, 소수점자리수)


In [132]:
weights = np.array([0.5, 0.3, 0.2])  # 종목별 투자 비중 (합계 1.0)
stock_returns = np.array([0.02, -0.01, 0.015])  # 종목별 오늘 수익률

result = weights@stock_returns

print(round(result*100,2),"%")

1.0 %


## 자주 만나는 오류 고쳐보기

넘파이를 쓰다 보면 shape이 맞지 않거나 axis를 잘못 지정해서 나는 오류를 자주 만나게 됩니다.  
아래 두 코드는 일부러 오류가 나거나 의도와 다른 결과가 나오도록 작성했습니다.  
원인을 찾아 직접 고쳐보세요.

### [LAB 3-4] 오류 수정 — shape 불일치   난이도 ★★☆   예상 소요 15분
힌트 · 오류 메시지의 (5,)와 (3,)이 각각 무엇의 shape인지 확인하세요.  
힌트 · discount가 5일치 할인율이어야 한다면 배열의 길이를 5로 맞춰야 합니다.  
힌트 · 수정 후 daily_sales * (1 - discount)가 정상적으로 계산되는지 확인하세요.  
TODO : 오류의 원인을 한 문장으로 설명하고, discount 배열을 올바르게 고쳐서 할인 적용 매출 배열을 출력하세요. 

```python
# 아래 코드를 실행하면 오류가 발생합니다
daily_sales = np.array([100, 120, 90, 110, 130])   # 5일치 매출
discount = np.array([0.1, 0.2, 0.15])              # 할인율 (3일치만 있음)

result = daily_sales * (1 - discount)
# ValueError: operands could not be broadcast together with shapes (5,) (3,)
```

In [133]:
daily_sales = np.array([100, 120, 90, 110, 130])   # 5일치 매출
discount = np.array([0.1, 0.2, 0.15,0,0])              # 할인율 (3일치만 있음)

result = daily_sales * (1 - discount)
# ValueError: operands could not be broadcast together with shapes (5,) (3,)

print(result)


[ 90.   96.   76.5 110.  130. ]


### [LAB 3-5] 오류 수정 — axis를 잘못 지정한 경우   난이도 ★★☆   예상 소요 15분
💰 시나리오 : 지점별 합계(3개 값)를 구하려 했는데 axis를 잘못 지정해서 날짜별 합계(5개 값)가 나왔습니다.  
힌트 · branch_sales.shape을 출력해서 axis=0과 axis=1이 각각 무엇을 의미하는지 확인하세요.  
힌트 · '지점별로 하나씩' 결과가 나오려면 어느 axis로 합쳐야 하는지 생각해보세요.  
TODO : axis 값을 올바르게 고쳐서 지점별 합계(3개 값)가 나오도록 수정하고, 매출이 가장 큰 지점을 argmax로 찾아 출력하세요.  



```python
branch_sales = np.array([
    [100, 120, 90, 110, 130],   # 강남지점
    [80, 95, 100, 85, 90],      # 종로지점
    [60, 70, 65, 75, 80],       # 홍대지점
])

total = branch_sales.sum(axis=0)   # 의도 : 지점별 합계
print(total)   # [240 285 255 270 300]  ← 5개가 나왔다? 지점은 3개인데?
```

In [134]:
branch_sales = np.array([
    [100, 120, 90, 110, 130],   # 강남지점
    [80, 95, 100, 85, 90],      # 종로지점
    [60, 70, 65, 75, 80],       # 홍대지점
])

total = branch_sales.sum(axis=1)   # 의도 : 지점별 합계
print(total)   # [240 285 255 270 300]  ← 5개가 나왔다? 지점은 3개인데?


[550 450 350]


In [138]:
branch_sales.shape
branch_sales

total.argmax()

np.int64(0)

## 배열 인덱싱과 슬라이싱

### 단일 요소 인덱싱

In [140]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[0], a[3])

b = np.array([[0, 1, 2], [3, 4, 5]])
print(b[1, 0])   # 3
print(b[1, 2])   # 5

c = [[0, 1, 2], [3, 4, 5]]
print(c[1][2])

0 3
3
5
5


### 슬라이싱

A[0:3]처럼 콜론(:)으로 인덱스 범위를 선택합니다. 시작 인덱스는 포함, 끝 인덱스는 포함하지 않습니다.

In [141]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[0:3])   # [0 1 2]

[0 1 2]


### 논리형(불리언) 인덱싱

In [145]:
a = np.arange(12).reshape(3, 4)
mask = a > 4
print(mask)          # 조건에 대한 True/False 배열
print(a[mask])       # 조건을 만족하는 값만 추출
a[mask] = 0          # 조건을 만족하는 값만 일괄 변경

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]


### 정수 배열 인덱싱

In [161]:
a = np.array(['a', 'b', 'c', 'd', 'e'])
i = np.array([0, 2, 4])
j = np.array([1,2,3])
h = np.arange(5)
print(a[i])          # ['a' 'c' 'e']
print(a[j])
print(a[h])

['a' 'c' 'e']
['b' 'c' 'd']
['a' 'b' 'c' 'd' 'e']


### [LAB 4-1] 인덱싱과 슬라이싱 기본   난이도 ★☆☆   예상 소요 10분
힌트 · a = np.array([0,1,2,3,4,5])에서 a[0], a[3], a[0:3]을 각각 출력하세요.  
힌트 · 2차원 배열 b를 만들어 b[1,0], b[1,2]도 출력해보세요.  
TODO : 1차원, 2차원 배열에서 인덱싱과 슬라이싱을 각각 실습하세요.

In [176]:
a = np.array([0,1,2,3,4,5])

index = np.array([[0],[3]])

print(a[index])

index = np.array([[1,0],[1,2]])

b = np.arange(6).reshape(2,3)
print(b[1,0],b[1,2])

[[0]
 [3]]
3 5


### [LAB 4-2] 급락일 추출 (논리형 인덱싱)   난이도 ★★☆   예상 소요 20분
💰 시나리오 : LAB 3-2에서 계산한 일별 수익률 배열에서 -1% 이하로 하락한 날만 골라내야 합니다.  
힌트 · returns 배열(LAB 3-2 결과)을 재사용하세요.  
힌트 · mask = returns <= -0.01 로 조건 배열을 만드세요.  
힌트 · returns[mask]로 급락일 수익률만 추출하고, mask.sum()으로 급락 발생 횟수도 출력하세요.  
TODO : -1% 이하 하락일의 수익률과 발생 횟수를 논리형 인덱싱으로 구해 출력하세요.


In [182]:
prices = np.array([71000, 71500, 70800, 72000, 72300, 71900])

today = prices[1:] # : index 1부터 끝까지
yesterday = prices[:-1] # : index 0<=index<끝

print(today, yesterday)

returns = (prices[1:] - prices[:-1]) / prices[:-1]

result = np.round(returns * 100, 2)

print(result)

#---

mask = result<=-0.1
sum(result[mask])

[71500 70800 72000 72300 71900] [71000 71500 70800 72000 72300]
[ 0.7  -0.98  1.69  0.42 -0.55]


np.float64(-1.53)

## 배열의 형태 변형하기

### reshape() — 새 배열 반환

In [144]:
a = np.arange(12).reshape(3, 4)
b = a.reshape(4, 3)   # 원본 a는 그대로, b는 새로운 배열
print(a.reshape(-1, 6))  # -1을 넣으면 나머지 크기를 자동 계산

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### resize() — 원본 자체를 변경

In [146]:
a = np.arange(12)
a.resize(3, 4)   # 반환값 없이 원본 a 자체가 바뀜

### 1차원으로 평탄화 · 전치(Transpose)

In [147]:
a = np.arange(12).reshape(3, 4)
print(a.ravel())      # 1차원으로 변경
print(a.reshape(-1))  # 위와 동일한 결과

A = np.arange(12).reshape(2, 6)
print(A.T)            # (2,6) → (6,2) 전치

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


### [LAB 5-1] 20일 종가를 4주 × 5일로 reshape   난이도 ★☆☆   예상 소요 15분
💰 시나리오 : 20거래일치 종가를 주 단위로 묶어서 보고 싶습니다.  
힌트 · daily_prices = np.arange(70000, 70000+20*100, 100) 처럼 20개 값을 만드세요.  
힌트 · daily_prices.reshape(4, 5)로 4주 x 5일 형태로 변형하세요.  
힌트 · reshape(-1, 5)로도 같은 결과가 나오는지 확인하세요.  
TODO : 20일치 종가를 (4,5) 형태로 reshape하고 결과를 출력하세요.

In [ ]:
daily_prices = np.arange(70000, 70000+20*100, 100)
# daily_prices = daily_prices.reshape(4, 5)
daily_prices = daily_prices.reshape(-1, 5)
daily_prices

array([[70000, 70100, 70200, 70300, 70400],
       [70500, 70600, 70700, 70800, 70900],
       [71000, 71100, 71200, 71300, 71400],
       [71500, 71600, 71700, 71800, 71900]])

### 전치(.T)와 3차원 배열 재구성

전치는 리포트 형식을 바꿀 때 자주 쓰이고, 3차원 배열은 '종목 × 주 × 요일'처럼 데이터를 더 세밀하게 나눠 담고 싶을 때 사용합니다.

In [148]:
# 5종목 x 4일 종가 행렬 -> 전치하면 4일 x 5종목
prices = np.arange(70000, 70000 + 20*100, 100).reshape(5, 4)
print(prices.shape)   # (5, 4)  ─ 종목이 행, 날짜가 열

report = prices.T
print(report.shape)   # (4, 5)  ─ 날짜가 행, 종목이 열 (리포트용 포맷)

(5, 4)
(4, 5)


In [149]:
# 3차원으로 재구성 : 5종목 x 4주 x 5일
daily = np.arange(100).reshape(5, 20)     # 5종목 x 20일(1차원 나열)
weekly = daily.reshape(5, 4, 5)           # 5종목 x 4주 x 5일
print(weekly.shape)   # (5, 4, 5)
print(weekly[0])      # 첫 번째 종목의 4주치 데이터만 확인

(5, 4, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### [LAB 5-2] 종목-날짜 리포트 포맷 전환 (전치)   난이도 ★★☆   예상 소요 15분
💰 시나리오 : 5종목 x 4일 종가 배열을, 날짜가 행이고 종목이 열인 '일별 리포트' 형태로 바꿔야 합니다.  
힌트 · prices = np.arange(70000, 70000+20*100, 100).reshape(5,4) 로 5종목x4일 배열을 만드세요.  
힌트 · .T 로 전치한 결과의 shape이 (4,5)로 바뀌는지 확인하세요.  
힌트 · 전치 전/후 배열을 각각 출력해서 값 배치가 어떻게 바뀌는지 비교하세요.  
TODO : prices 배열을 전치해서 (4,5) 형태의 리포트 배열을 만들고, 전치 전후를 함께 출력해 비교하세요.

### [LAB 5-3] 3차원 재구성과 reshape vs resize 검증   난이도 ★★★   예상 소요 20분 
💰 시나리오 : 5종목의 20일치 종가를 4주 단위 3차원 배열로 재구성하고, reshape과 resize의 차이를 직접 확인해야 합니다.  
힌트 · daily = np.arange(100).reshape(5,20) 로 5종목x20일 배열을 만드세요.  
힌트 · weekly = daily.reshape(5,4,5) 로 3차원(5종목x4주x5일)으로 재구성하세요.  
힌트 · daily.reshape(5,4,5) 실행 후 daily 자체는 그대로인지, weekly는 별개의 새 배열인지 확인하세요.  
힌트 · daily.resize(5,4,5)를 실행하면 daily 자체가 바뀌는지도 확인해보세요 (resize는 반환값이 없습니다).  
TODO : reshape으로 3차원 배열을 만든 뒤 원본이 바뀌지 않음을 확인하고, resize로 원본이 직접 바뀌는 것도 확인해 두 함수의 차이를 코드로 증명하세요.

In [184]:
daily = np.arange(100).reshape(5,20)

weekly = daily.reshape(5,4,5)

daily.reshape(5,4,5)
print(daily,weekly)

daily.resize(5,4,5)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]] [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


## 배열 합치고 분할하기

In [150]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array([5, 6, 7, 8]).reshape(2, 2)

print(np.vstack((a, b)))   # 수직으로 합치기
print(np.hstack((a, b)))   # 수평으로 합치기

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [151]:
a = np.arange(12).reshape(2, 6)
print(np.vsplit(a, 2))     # 수직으로 분할
print(np.hsplit(a, 3))     # 수평으로 분할

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


### [LAB 6-1] 두 지점 매출 배열 합치기   난이도 ★★☆   예상 소요 15분
💰 시나리오 : 강남지점, 종로지점 각각의 주간 매출 배열을 하나로 합쳐 전체 현황표를 만듭니다.  
힌트 · gangnam, jongno 두 (1,5) 형태 배열을 만드세요.  
힌트 · np.vstack으로 세로로 합쳐 (2,5) 형태의 전체 현황 배열을 만드세요.  
TODO : 두 지점 매출 배열을 vstack으로 합쳐 출력하세요.

In [193]:
gangnam = np.array([1,2,3,4,5])
jongno = np.array([9,8,7,6,5])

result = np.vstack((gangnam,jongno))

result2 = np.hstack((gangnam,jongno))

arr1, arr2 = np.vsplit(result,2)
arr3, arr4 = np.hsplit(result2,2)


print(result)
print(result2)

print(arr1,arr2)
print(arr3, arr4)

[[1 2 3 4 5]
 [9 8 7 6 5]]
[1 2 3 4 5 9 8 7 6 5]
[[1 2 3 4 5]] [[9 8 7 6 5]]
[1 2 3 4 5] [9 8 7 6 5]


## np.split / array_split — 원하는 개수로 나누기

np.split은 정확히 나누어떨어져야 하지만, np.array_split은 나머지를 자동으로 분배해 균등하지 않아도 나눌 수 있습니다

In [152]:
daily = np.arange(70000, 70000+20*100, 100)   # 20일치 종가

weeks = np.split(daily, 4)          # 정확히 4등분 (5일씩)
print(len(weeks), weeks[0])

# 20을 3으로 나누면 나누어떨어지지 않음
groups = np.array_split(daily, 3)   # 7,7,6 처럼 자동 분배
print([len(g) for g in groups])

groups

4 [70000 70100 70200 70300 70400]
[7, 7, 6]


[array([70000, 70100, 70200, 70300, 70400, 70500, 70600]),
 array([70700, 70800, 70900, 71000, 71100, 71200, 71300]),
 array([71400, 71500, 71600, 71700, 71800, 71900])]

### [LAB 6-2] 20일 종가를 주 단위로 분할   난이도 ★☆☆   예상 소요 10분
💰 시나리오 : 20거래일 종가를 4주 단위로 나누어 주차별로 따로 관리하고 싶습니다.  
힌트 · daily = np.arange(70000, 70000+20*100, 100) 로 20개 값을 만드세요.  
힌트 · np.split(daily, 4)로 4등분한 뒤, 각 그룹의 길이와 첫 번째 그룹을 출력하세요.  
힌트 · 5장의 reshape(4,5) 결과와 비교해 배열 형태가 어떻게 다른지 확인해보세요.  
TODO : daily 배열을 np.split으로 4등분하고, 각 주차 데이터를 순서대로 출력하세요.

In [195]:
daily = np.arange(70000, 70000+20*100, 100)
print(daily)
weekly = np.split(daily,4)

for i, data in enumerate(weekly,1):
  print(f"{i}주차 | {data}")

[70000 70100 70200 70300 70400 70500 70600 70700 70800 70900 71000 71100
 71200 71300 71400 71500 71600 71700 71800 71900]
1주차 | [70000 70100 70200 70300 70400]
2주차 | [70500 70600 70700 70800 70900]
3주차 | [71000 71100 71200 71300 71400]
4주차 | [71500 71600 71700 71800 71900]


### concatenate로 유연하게 합치기 — 신규 데이터 추가

실무에서는 지점이 새로 생기거나 날짜가 추가되는 경우가 많습니다.  
np.concatenate는 axis를 지정해 어느 방향으로 합칠지 유연하게 정할 수 있습니다.

In [ ]:
gangnam = np.array([[100, 120, 90, 110, 130]])   # (1,5)
jongno  = np.array([[80, 95, 100, 85, 90]])      # (1,5)

branch_sales = np.concatenate([gangnam, jongno], axis=0)   # (2,5) 지점 추가
print(branch_sales.shape)

# 신규 지점(홍대)이 나중에 추가된 경우
hongdae = np.array([[60, 70, 65, 75, 80]])
branch_sales = np.concatenate([branch_sales, hongdae], axis=0)
print(branch_sales.shape)   # (3,5)

(2, 5)
(3, 5)


### [LAB 6-3] 신규 지점 매출 추가와 지점별/일자별 합계 비교   난이도 ★★★   예상 소요 20분
💰 시나리오 : 강남·종로 2개 지점 매출표에 홍대지점이 새로 추가되었습니다.  
  전체 매출 배열을 갱신하고, 지점별 합계와 일자별 합계를 axis로 구분해 계산해야 합니다.  
힌트 · LAB 6-1의 강남·종로 배열을 재사용해 (2,5) 배열을 만드세요.  
힌트 · hongdae = np.array([[60,70,65,75,80]]) 를 만들고 np.concatenate로 axis=0에 이어붙이세요.  
힌트 · 지점별 합계는 axis=1, 일자별 합계는 axis=0 중 어느 쪽인지 shape을 보며 판단하세요.  
힌트 · 가장 매출이 큰 지점과 가장 매출이 큰 날짜를 각각 argmax로 찾아보세요.  
TODO : 홍대지점 데이터를 concatenate로 추가한 뒤, 지점별 합계·일자별 합계·최대 매출 지점/날짜를 모두 출력하세요.  

In [215]:
array = np.concatenate([gangnam, jongno],axis=0)
hongdae = np.array([60,70,65,75,80])

array = np.concatenate([array,[hongdae]],axis=0)


print(array)
print(array.shape)

branch_total = np.sum(array,axis=1)
daily_total = np.sum(array,axis=0)

branch_index = branch_total.argmax()
branch_max = branch_total[branch_index]
branch_max_day = daily_total[branch_index]

print(f"업장 : {branch_total}-{branch_max}")
print(f"일자 : {daily_total}-{branch_max_day}")

[[100 120  90 110 130]
 [ 80  95 100  85  90]
 [ 60  70  65  75  80]]
(3, 5)
업장 : [550 450 350]-550
일자 : [240 285 255 270 300]-240


## 실전 데이터 불러오기와 결측치 처리

실무에서는 배열을 코드로 직접 입력하기보다 CSV 파일에서 불러오는 경우가 대부분입니다.  
이번 절에서는 파일에서 배열을 불러오는 방법과, 중간중간 비어 있는 값(결측치)을 처리하는 방법을 살펴봅니다.

### np.loadtxt vs np.genfromtxt

np.loadtxt는 빠르지만 빈 칸(결측치)이 있으면 오류가 납니다.  
np.genfromtxt는 조금 느리지만 빈 칸을 자동으로 nan(Not a Number)으로 처리해줘서 실무 데이터에 더 적합합니다.

In [241]:
# stock_prices.csv 예시 (일부 결측치 포함)
# 삼성전자,SK하이닉스,카카오,NAVER,LG화학
# 71000,120000,45000,210000,410000
# 71500,,45500,209000,412000
# 70800,121000,,208500,409000

np.set_printoptions(suppress=True)

data = np.genfromtxt("stock_prices.csv", delimiter=",", skip_header=1) #, filling_values=1
print(data)          # 빈 칸은 자동으로 nan이 됩니다
print(data.dtype)    # nan을 표현하려면 float64 타입이어야 합니다

try:
  data2 = np.loadtxt("stock_prices.csv",delimiter=",",skiprows=1)
  print(data2)
  print(data2.dtype)
except ValueError as e:
  print(e)

[[ 71000. 120000.  45000. 210000. 410000.]
 [ 71500.     nan  45500. 209000. 412000.]
 [ 70800. 121000.     nan 208500. 409000.]]
float64
could not convert string '' to float64 at row 1, column 2.


💡 지수 표현을 끄는 설정 (suppress=True)  
np.set_printoptions(suppress=True)

## 결측치(NaN) 찾아서 채우기

In [242]:
print(np.isnan(data))          # 결측치 위치를 True/False로 표시
print(np.isnan(data).sum())    # 결측치 개수

col_mean = np.nanmean(data, axis=1)        # 결측치를 제외한 열(종목)별 평균
print("col_mean : ",col_mean)
inds = np.where(np.isnan(data))
print("np.where(np.isnan(data)) : ",inds)
data[inds] = np.take(col_mean, inds[0])    # 결측치를 해당 열 평균으로 채우기

print(data)

[[False False False False False]
 [False  True False False False]
 [False False  True False False]]
2
col_mean :  [171200. 184500. 202325.]
np.where(np.isnan(data)) :  (array([1, 2]), array([1, 2]))
[[ 71000. 120000.  45000. 210000. 410000.]
 [ 71500. 184500.  45500. 209000. 412000.]
 [ 70800. 121000. 202325. 208500. 409000.]]


주의 :  
np.nanmean, np.nansum처럼 nan으로 시작하는 함수들은 결측치를 무시하고 계산합니다.  
일반 mean()/sum()을 쓰면 결측치가 하나만 있어도 결과 전체가 nan이 되어버리니 주의하세요.


### [LAB 7-1] 결측치 있는 종가 데이터 정제   난이도 ★★☆   예상 소요 20분
💰 시나리오 : 데이터팀에서 받은 5종목 20일 종가 데이터에 전송 오류로 일부 결측치가 섞여 있습니다. 분석 전에 결측치를 열(종목)별 평균으로 채워야 합니다.  
힌트 · data = np.array([[71000,120000,45000,210000,410000],[71500,np.nan,45500,209000,412000],[70800,121000,np.nan,208500,409000],[72000,119500,45200,np.nan,411000]]) 로 결측치가 섞인 배열을 만드세요.  
힌트 · np.isnan(data).sum()으로 전체 결측치 개수를 확인하세요.  
힌트 · col_mean = np.nanmean(data, axis=0)로 종목별 평균을 구하세요.  
힌트 · inds = np.where(np.isnan(data)) 후 data[inds] = np.take(col_mean, inds[1])로 결측치를 채우세요.  
TODO : data 배열의 결측치 개수를 출력하고, 각 종목의 평균값으로 결측치를 채운 최종 배열을 출력하세요.


지금처럼 결측치를 직접 찾아 채우는 과정은 넘파이만으로는 다소 번거롭습니다. 3일차에 배울 Pandas는 이런 과정을 fillna() 같은 메서드 한 줄로 처리할 수 있게 해 줍니다.

## 종합 실습 — 5종목 주가 포트폴리오 분석

### [종합 LAB] 5종목 20일 주가 데이터 분석   난이도 ★★★   예상 소요 50분
💰 시나리오 : 5개 종목의 20거래일 종가 데이터가 있습니다. 종목별 수익률, 변동성, 최고/최저 수익률 종목을 넘파이만으로 분석해야 합니다.  
힌트 · prices = np.random.randint(50000, 200000, size=(5, 20))로 5종목×20일 임의 종가 행렬을 만드세요 (실무에서는 3일차 Pandas에서 실제 CSV로 대체합니다).  
힌트 · 일별 수익률 행렬 returns = (prices[:, 1:] - prices[:, :-1]) / prices[:, :-1] 를 슬라이싱으로 계산하세요 (열이 날짜, 행이 종목).  
힌트 · 종목별 평균 수익률은 returns.mean(axis=1), 종목별 변동성(리스크)은 returns.std(axis=1)로 axis를 지정해 구하세요.  
힌트 · np.argmax()/np.argmin()으로 평균 수익률이 가장 높은/낮은 종목의 인덱스를 찾아 출력하세요.  
힌트 · weights = np.array([0.3, 0.25, 0.2, 0.15, 0.1])로 포트폴리오 비중을 정하고, weights @ returns.mean(axis=1)로 포트폴리오 기대수익률을 계산하세요.  
TODO : 종목별 평균 수익률/변동성, 최고·최저 수익률 종목, 포트폴리오 기대수익률까지 순서대로 계산해 출력하세요.

In [255]:
prices = np.random.randint(50000, 200000, size=(5, 20))
returns = (prices[:, 1:] - prices[:, :-1]) / prices[:, :-1]
# print(f"월별 수익률 : {returns}")

print(f"종목별 평균 수익률 : {returns.mean(axis=1)}")
print(f"종목별 변동성 : {returns.std(axis=1)}")

argmax = np.argmax(returns.mean(axis=1))
argmin = np.argmin(returns.mean(axis=1))
print(f"argmax: {argmax}, argmin: {argmin}")

weights = np.array([0.3, 0.25, 0.2, 0.15, 0.1])
print(f"기대 수익률: {weights @ returns.mean(axis=1)}")


종목별 평균 수익률 : [0.18106374 0.21161463 0.07256175 0.19404533 0.16578   ]
종목별 변동성 : [0.7585064  0.72924927 0.45877653 0.62547829 0.72886882]
argmax: 1, argmin: 2
기대 수익률: 0.1674199284784253
