# 넘파이


NumPy는 파이썬에서 대규모 수치 데이터를 빠르게 처리하기 위한 배열 연산 라이브러리입니다.  
Pandas, 시각화, 머신러닝 라이브러리 대부분이 내부적으로 NumPy 배열을 사용합니다.

In [109]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [110]:
alist = [1,2,3,4,5] * 3

print(alist)

blist = np.array([1,2,3,4,5])*3

print(blist)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


In [111]:
import numpy

arr = [71000, 71500, 70800, 72000, 72300]
prices = numpy.array(arr)

type(arr), type(prices), arr*2, prices*2


(list,
 numpy.ndarray,
 [71000, 71500, 70800, 72000, 72300, 71000, 71500, 70800, 72000, 72300],
 array([142000, 143000, 141600, 144000, 144600]))

## 넘파이 배열, ndarray

### 1차원, 2차원, 3차원 배열

In [112]:
arr_1 = np.array([1, 2, 3, 4, 5])            # 1차원 # axis = 0
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])     # 2차원 (행렬) # axis = 0, 1
arr_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3차원 # axis = 0, 1, 2

arr_1.shape, arr_2.shape, arr_3.shape

((5,), (2, 3), (2, 2, 2))

### 넘파이 배열의 데이터 타입(dtype)

In [113]:
a = np.array([1, 2, 3])
print(a.dtype)                    # int64 : data가 64bit 정수

b = np.array([1, 2, 3], dtype=float)
print(b.dtype)                    # float64 : data가 64bit 실수

a.itemsize # 8바이트 정수

int64
float64


8

### 넘파이 배열의 속성

|속성|설명|
|--|--|
|ndarray.shape|배열의 각 축(axis)의 크기|
|ndarray.ndim|축의 개수(차원)|
|ndarray.dtype|각 요소의 타입|
|ndarray.itemsize|각 요소 타입의 byte 크기|
|ndarray.size|전체 요소의 개수|

In [114]:
a = np.arange(6).reshape(2, 3)
print(a.shape)     # (3, 4)
print(a.ndim)      # 2
print(a.dtype)     # int64
print(a.itemsize)  # 8
print(a.size)      # 12
print(a)

(2, 3)
2
int64
8
6
[[0 1 2]
 [3 4 5]]


In [115]:
arr1 = np.array([1,0,3,5])

arr1, arr1.shape, np.sum(arr1,axis=0)

(array([1, 0, 3, 5]), (4,), np.int64(9))

In [116]:
arr2 = np.array([[3.3, 2.7, 0.1, 2.1],[0.1, 9.9, 5.4, 6.2]])

arr2, arr2.shape
# 2차원에선 axis = 0이 행방향(열 중심) => 결과: 행 사라짐
np.sum(arr2,axis=0)
# axis = 1 열방향(행 중심) => 결과: 열이 사라짐
np.sum(arr2, axis=1)

array([ 8.2, 21.6])

In [117]:
arr3 = np.arange(24).reshape(2,3,4)
print(arr3)
print("--axis=0--")
print(np.sum(arr3, axis=0))
print("--axis=1--")
print(np.sum(arr3, axis=1))
print("--axis=2--")
print(np.sum(arr3, axis=2))
print("--------")

arr2_1 = np.array([[ 0,  1,  2,  3],
  [ 4,  5,  6,  7],
  [ 8,  9, 10, 11]])
print(arr2_1)
print("-@axis=0@-")
print(np.sum(arr2_1, axis=0))
print("-@axis=1@-")
print(np.sum(arr2_1, axis=1))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--axis=0--
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
--axis=1--
[[12 15 18 21]
 [48 51 54 57]]
--axis=2--
[[ 6 22 38]
 [54 70 86]]
--------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-@axis=0@-
[12 15 18 21]
-@axis=1@-
[ 6 22 38]


### 넘파이 배열의 장점 — 요소별 연산과 브로드캐스팅

파이썬 리스트에 *2를 하면 리스트가 2배로 이어붙여지지만, 넘파이 배열은 각 요소에 2를 곱합니다.  
이렇게 배열의 크기가 달라도 작은 배열을 자동으로 확장해 연산하는 것을 브로드캐스팅이라고 합니다.

In [118]:
py_list = [1, 2, 3]
print(py_list * 2)        # [1, 2, 3, 1, 2, 3]  (리스트 반복)

np_arr = np.array([1, 2, 3])
print(np_arr * 2)         # [2 4 6]             (브로드캐스팅)


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [119]:
# 3종목 x 4일 종가 (3,4)
prices = np.array([
  [71000, 71500, 70800, 72000],
  [62000, 61800, 62200, 61500],
  [155000, 154000, 156000, 153000],
])

# 날짜별 환율
fee = np.array([100,100,150,150])

prices.shape, fee.shape

# 계산하면 fee.shape가 복제되어 3열(3줄)의 2차원으로 변형

print(prices-fee)

fee_rate = np.array([[0.001],[0.0015],[0.002]])
fee_rate.shape

# 계산시에 복제 => [[a,a,a,a],[b,b,b,b],[c,c,c,c]]
print(prices * fee_rate)

[[ 70900  71400  70650  71850]
 [ 61900  61700  62050  61350]
 [154900 153900 155850 152850]]
[[ 71.    71.5   70.8   72.  ]
 [ 93.    92.7   93.3   92.25]
 [310.   308.   312.   306.  ]]


### 다양한 배열 생성 함수

|함수|설명|
|--|--|
|np.zeros(shape)|모든 요소를 0으로 초기화|
|np.ones(shape)|모든 요소를 1로 초기화|
|np.empty(shape)|초기화되지 않은 배열(임의값)|
|np.arange(시작,끝,간격)|일정 간격 배열, 끝값 미포함|
|np.linspace(시작,끝,개수)|구간을 균등 분할, 끝값 포함|


In [120]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=int)
np.arange(10, 30, 5)          # [10 15 20 25]
np.linspace(1, 10, 10)        # 1~10을 10개로 균등 분할

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [121]:
np.array([1,2,3])
np.arange(24).reshape(2,3,4)

np.zeros((2,3,4))

np.empty((2,3,4))

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### [LAB 2-1] 배열 생성과 속성 확인   난이도 ★☆☆   예상 소요 15분
💰 시나리오 : 5개 종목의 오늘 종가를 배열로 만들고 속성을 확인합니다.  
힌트 · closes = np.array([71000, 62000, 155000, 210000, 89000])를 만드세요.  
힌트 · shape, ndim, dtype, size를 각각 출력하세요.  
힌트 · np.zeros(5)로 초기 매수량 배열을 만들어보세요.  
TODO : closes 배열을 만들고 속성 4가지와 zeros(5) 배열을 출력하세요.


In [122]:
closes = np.array([71000, 62000, 155000, 210000, 89000])

print(closes.shape, closes.ndim, closes.dtype, closes.size)

np.zeros(5)

(5,) 1 int64 5


array([0., 0., 0., 0., 0.])

### [LAB 2-2] 원화 종가 → 달러 환산 (브로드캐스팅)   난이도 ★★☆   예상 소요 15분
💰 시나리오 : 해외 리포트용으로 원화 종가 배열을 달러로 환산해야 합니다.  
힌트 · krw_prices = np.array([71000, 62000, 155000, 210000, 89000])를 만드세요.  
힌트 · 환율 exchange_rate = 1380.0으로 나누면 브로드캐스팅으로 전체 배열이 한 번에 환산됩니다.  
힌트 · usd_prices = krw_prices / exchange_rate 를 출력하세요.  
TODO : krw_prices를 달러로 환산한 usd_prices 배열을 브로드캐스팅으로 계산해 출력하세요.  


exchange_rate라는 1개짜리 단일 값(Scalar)을 연산할 때,  
크기를 맞추기 위해 스칼라 값이 배열의 크기만큼 자동으로 확장되어 요소별(Element-wise) 연산이 진행됩니다.  
[1380.0,  1380.0,  1380.0,  1380.0,  1380.0 ]  (exchange_rate 가 브로드캐스팅 됨)


In [123]:
krw_prices = np.array([71000, 62000, 155000, 210000, 89000])

exchange_rate = 1380.0

usd_prices = krw_prices / exchange_rate

print(usd_prices)

[ 51.44927536  44.92753623 112.31884058 152.17391304  64.49275362]


## 넘파이 배열로 다양하게 연산하기

### 요소별 연산 — 사칙연산 · 행렬곱 · 비교연산

In [124]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a - b)   # [-3 -3 -3]
print(a * b)   # [4 10 18]  (요소별 곱셈)
print(a / b)   # [0.25 0.4 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [125]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print(A * B)   # 요소별 곱셈
print(A @ B)   # 행렬 곱셈 (내적)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [126]:
A = np.array([1, 2, 3])
B = np.array([2])
print(A > B)   # [False False True]

[False False  True]


### 수학 함수 · 집계 함수와 벡터화 연산

In [127]:
a = np.array([1, 4, 9])
print(np.sqrt(a))   # [1. 2. 3.]

[1. 2. 3.]


In [128]:
a = np.arange(8).reshape(2, 4) ** 2
print(a)
print(a.sum())      # 전체 합
print(a.mean())     # 전체 평균
print(a.min())      # 최솟값
print(a.max())      # 최댓값
print(a.cumsum())   # 누적합
print(a.argmax())   # 최댓값의 인덱스

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


### 집계 함수에 축(axis) 사용하기

주의:  
axis=0은 '행 방향으로 내려가며' 즉 열마다 하나의 결과를, axis=1은 '열 방향으로 가로질러' 즉 행마다 하나의 결과를 만듭니다.  
처음에는 헷갈리기 쉬우니 결과의 shape을 함께 확인하는 습관을 들이세요.

In [129]:
a = np.array([[0, 1, 4, 9], [16, 25, 36, 49]])

print(a.sum(axis=0))   # 열 기준 : [16 26 40 58]
print(a.sum(axis=1))   # 행 기준 : [14 126]

[16 26 40 58]
[ 14 126]


### [LAB 3-1] 사칙연산과 비교연산   난이도 ★☆☆   예상 소요 15분
💰 시나리오 : 두 종목의 5일 종가 배열로 가격 차이(스프레드)를 계산합니다.  
힌트 · stock_a, stock_b 두 배열(각 5개)을 만드세요.  
힌트 · 스프레드 = stock_a - stock_b를 계산하세요.  
힌트 · stock_a > stock_b 비교 연산으로 A가 더 비쌌던 날을 True/False로 확인하세요.  
TODO : 두 종목 배열을 만들고 스프레드와 비교 연산 결과를 각각 출력하세요.  

In [130]:
stock_a = np.array([2,0,4,1,6])
stock_b = np.array([1,2,3,4,5])

stock = stock_a-stock_b

result = stock_a>stock_b

print(stock, result)

[ 1 -2  1 -3  1] [ True False  True False  True]


### [LAB 3-2] 일별 수익률 계산 (벡터화 연산)   난이도 ★★★   예상 소요 25분
💰 시나리오 : 종가 배열만으로 반복문 없이 일별 수익률을 계산해야 합니다. 수익률 = (오늘종가 - 어제종가) / 어제종가  
힌트 · prices = np.array([71000, 71500, 70800, 72000, 72300, 71900])처럼 6일치 종가를 만드세요.  
힌트 · 오늘 종가는 prices[1:], 어제 종가는 prices[:-1] 슬라이싱으로 얻을 수 있습니다. 두 배열의 길이가 같아 요소별 연산이 가능합니다.  
힌트 · returns = (prices[1:] - prices[:-1]) / prices[:-1] 로 일별 수익률 배열을 구하세요.  
힌트 · np.round(returns * 100, 2)로 퍼센트(%)로 변환해 출력하세요.  
TODO : for문 없이 슬라이싱과 벡터화 연산만으로 일별 수익률 배열을 계산해 퍼센트로 출력하세요.  


[71500 70800 72000 72300 71900]  
[71000 71500 70800 72000 72300]  




In [131]:
prices = np.array([71000, 71500, 70800, 72000, 72300, 71900])

today = prices[1:] # : index 1부터 끝까지
yesterday = prices[:-1] # : index 0<=index<끝

print(today, yesterday)

returns = (prices[1:] - prices[:-1]) / prices[:-1]

result = np.round(returns * 100, 2)

print(result)


#---

result = []
prices = [71000, 71500, 70800, 72000, 72300, 71900]

for index, data in enumerate(prices):
  if index!=0 :
    today = data
    yesterday = prices[index-1]
    returns = (today-yesterday)/yesterday
    result.append(returns)

result = [round(result*100,2) for result in result]

print(result)

[71500 70800 72000 72300 71900] [71000 71500 70800 72000 72300]
[ 0.7  -0.98  1.69  0.42 -0.55]
[0.7, -0.98, 1.69, 0.42, -0.55]


### [LAB 3-3] 포트폴리오 수익률 (행렬곱)   난이도 ★★★   예상 소요 20분
💰 시나리오 : 3종목에 대해 비중을 다르게 투자한 포트폴리오의 전체 수익률을 한 번에 계산합니다.  
힌트 · weights = np.array([0.5, 0.3, 0.2])  # 종목별 투자 비중 (합계 1.0)  
힌트 · stock_returns = np.array([0.02, -0.01, 0.015])  # 종목별 오늘 수익률  
힌트 · 포트폴리오 전체 수익률은 두 벡터의 내적(@ 연산 또는 np.dot)으로 한 번에 계산됩니다.  
TODO : weights와 stock_returns의 행렬곱(@ 연산)으로 포트폴리오 전체 수익률을 계산해 퍼센트로 출력하세요.  

round( 값, 소수점자리수)


In [132]:
weights = np.array([0.5, 0.3, 0.2])  # 종목별 투자 비중 (합계 1.0)
stock_returns = np.array([0.02, -0.01, 0.015])  # 종목별 오늘 수익률

result = weights@stock_returns

print(round(result*100,2),"%")

1.0 %


## 자주 만나는 오류 고쳐보기

넘파이를 쓰다 보면 shape이 맞지 않거나 axis를 잘못 지정해서 나는 오류를 자주 만나게 됩니다.  
아래 두 코드는 일부러 오류가 나거나 의도와 다른 결과가 나오도록 작성했습니다.  
원인을 찾아 직접 고쳐보세요.

### [LAB 3-4] 오류 수정 — shape 불일치   난이도 ★★☆   예상 소요 15분
힌트 · 오류 메시지의 (5,)와 (3,)이 각각 무엇의 shape인지 확인하세요.  
힌트 · discount가 5일치 할인율이어야 한다면 배열의 길이를 5로 맞춰야 합니다.  
힌트 · 수정 후 daily_sales * (1 - discount)가 정상적으로 계산되는지 확인하세요.  
TODO : 오류의 원인을 한 문장으로 설명하고, discount 배열을 올바르게 고쳐서 할인 적용 매출 배열을 출력하세요. 

```python
# 아래 코드를 실행하면 오류가 발생합니다
daily_sales = np.array([100, 120, 90, 110, 130])   # 5일치 매출
discount = np.array([0.1, 0.2, 0.15])              # 할인율 (3일치만 있음)

result = daily_sales * (1 - discount)
# ValueError: operands could not be broadcast together with shapes (5,) (3,)
```

In [133]:
daily_sales = np.array([100, 120, 90, 110, 130])   # 5일치 매출
discount = np.array([0.1, 0.2, 0.15,0,0])              # 할인율 (3일치만 있음)

result = daily_sales * (1 - discount)
# ValueError: operands could not be broadcast together with shapes (5,) (3,)

print(result)


[ 90.   96.   76.5 110.  130. ]


### [LAB 3-5] 오류 수정 — axis를 잘못 지정한 경우   난이도 ★★☆   예상 소요 15분
💰 시나리오 : 지점별 합계(3개 값)를 구하려 했는데 axis를 잘못 지정해서 날짜별 합계(5개 값)가 나왔습니다.  
힌트 · branch_sales.shape을 출력해서 axis=0과 axis=1이 각각 무엇을 의미하는지 확인하세요.  
힌트 · '지점별로 하나씩' 결과가 나오려면 어느 axis로 합쳐야 하는지 생각해보세요.  
TODO : axis 값을 올바르게 고쳐서 지점별 합계(3개 값)가 나오도록 수정하고, 매출이 가장 큰 지점을 argmax로 찾아 출력하세요.  



```python
branch_sales = np.array([
    [100, 120, 90, 110, 130],   # 강남지점
    [80, 95, 100, 85, 90],      # 종로지점
    [60, 70, 65, 75, 80],       # 홍대지점
])

total = branch_sales.sum(axis=0)   # 의도 : 지점별 합계
print(total)   # [240 285 255 270 300]  ← 5개가 나왔다? 지점은 3개인데?
```

In [134]:
branch_sales = np.array([
    [100, 120, 90, 110, 130],   # 강남지점
    [80, 95, 100, 85, 90],      # 종로지점
    [60, 70, 65, 75, 80],       # 홍대지점
])

total = branch_sales.sum(axis=1)   # 의도 : 지점별 합계
print(total)   # [240 285 255 270 300]  ← 5개가 나왔다? 지점은 3개인데?


[550 450 350]


In [135]:
branch_sales.shape
branch_sales


array([[100, 120,  90, 110, 130],
       [ 80,  95, 100,  85,  90],
       [ 60,  70,  65,  75,  80]])